# Generated by Django 5.0.7 on 2024-07-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_capture_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recording', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='CapturedImage',
        ),
    ]
